# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.ssh.insert_key = true 
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end 
  config.vm.define "app1" do |app|
    app.vm.hostname = "app1.dev"
    app.vm.box = "centos/7"
    app.vm.network "private_network", ip: "192.168.0.201"
  end
  config.vm.define "app2" do |app|
    app.vm.hostname = "app2.dev"
    app.vm.box = "centos/7"
    app.vm.network "private_network", ip: "192.168.0.202"
  end
  config.vm.define "db" do |db|
    db.vm.hostname = "db1.dev"
    db.vm.box = "centos/7"
    db.vm.network "private_network", ip: "192.168.0.203"
  end
end
