--- 
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: 1. Installing nginx 
      apt: name=nginx update_cache=yes

    - name: 2. Copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: 3. Enable config file
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: 4.Copying index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: 5.Restart nginx 
      service: name=nginx state=restarted
