---
#task for code deployment
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install packages
  composer:
    command: install
    working_dir: "{{ app_work_dir }}"
  tags:
    - code-deploy

- name: Reset any local changes
  shell: "cd {{app_work_dir}} && git reset --hard"
  tags:
    - code-deploy

- name: update repo - pull the latest changes
  git:
    repo: "{{repo_git_url}}"
    dest: "{{app_work_dir}}"
    update: yes
    version: master
  tags:
    - code-deploy


- name: Run artisan migrate
  shell: "php {{app_work_dir}} artisan migrate"
  tags:
    - code-deploy

- name: Run clear cached routes
  shell: "php {{app_work_dir}} artisan route:clear"
  tags:
    - code-deploy

- name: Run clear cache
  shell: "php {{app_work_dir}} artisan cache:clear"
  tags:
    - code-deploy

- name: Update File Permissions
  file: dest={{app_work_dir}}  mode=0755 recurse=yes
  tags:
    - code-deploy
    - file-permissions

- name: Update storage Permissions
  file: dest={{app_work_dir}}storage  mode=0777 recurse=yes
  tags:
    - code-deploy
    - file-permissions

- name: Copy lara env file
  become: true
  template:
    src: templates/env.conf
    dest: "{{app_work_dir}}/.env"
  tags:
      - env-file

