---
- name: A1. Update the repos 
  apt: update_cache=yes cache_valid_time=3600

- name: 1. Install Apache
  apt: name=apache2 state=present
- name: 1a. Install ppa-repo 
  apt_repository: repo="ppa:ondrej/php"

- name: 1b. Update the repos 
  apt: update_cache=yes cache_valid_time=3600

- name: 2. Install PHP modules for Apache
  apt: name=libapache2-mod-php state=present

- name: 3. start Apache
  service: name=apache2 state=restarted enabled=yes

- name: 4. Install Hello World PHP script
  copy: "src=index.php dest=/var/www/html/index.php mode=0664"
