---
- set_fact:
- name: 1. Adding Ondrej Repo
  apt_repository: repo="ppa:ondrej/php" update_cache=yes

- name: 2. Installing PHP with other dependencies
  apt:
    state: present
    name:
      - git 
      - curl
      - unzip
      - apache2
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-json
      - php-mysql
      - php-mbstring


- name: 3. Installing MySQL server
  apt:
    state: present
    name:
      - mysql-server
      - python-mysqldb

- name: 4. Start Apache, MySQL and PHP
  service: name= {{ item }} state=started enabled=yes 
  with_items:
    - apache2
    - mysql

- name: 5. Enable Apache module
  apache2_module: name=rewrite state=present
  notify: restart apache

- name: 6. Adding Vhost for Drupal
  template:
    src: "files/drupal.dev.conf.js"
    dest: "/etc/apache2/sites-available/drupal.dev.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: 7. Sym link vhost to enabled-sites
  file:
    src: "/etc/apache2/sites-available/drupal.dev.conf"
    dest: "/etc/apache2/sites-enabled/drupal.dev.conf"
    state: link
  notify: restart apache

- name: Remove default vhost file
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache

- name: Opcache memory setting
  lineinfile:
    dest: "/etc/php/7.2/apache2/conf.d/10-opcache.ini"
    regexp: "^opcache.memory_consumption"
    line: "opcache.memory_consumption = 96"
    state: present
  notify: restart apache

- name: Remove test DB from MySQL
  mysql_db: db=test state=present

- name: Create Database 
  mysql_db: "db=drupal state=present"

- name: Create MySQL user 
  mysql_user:
    name: "drupal"
    password: "1234"
    priv: "drupal.*:ALL"
    host: localhost
    state: present

- name: Download PHP Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer 
  command: >
    php compose-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Git clone drush 
  git:
    repo: https://github.com/drush-ops/drush.git
    version: 8
    dest: /opt/drush

- name: Install Drush dependencies with Composer
  shell: >
    /usr/loca/bin/composer install
    chdir=/opt/drush
    creates=/opt/drush/vendor/autoload.php

- name: Create Drush Sym link
  file:
    src: /opt/drush/drush
    dest: /usr/local/bin/drush
    state: link

- name: Git clone Drupal core
  git:
    repo: https://github.com/drupal/drupal.git
    version: '8.6.5'
    dest: /var/www/drupal-8.6.5-dev

- name: Install Drupal dependencies with Composer.
  shell: >
    /usr/local/bin/composer install
    chdir=/var/www/drupal-8.6.5-dev
    creates=/var/www/drupal-8.6.5-dev/vendor/autoload.php

- name: Install Drupal.
  command: >
    drush si -y --site-name="{{ drupal_site_name }}"
    --account-name=admin
    --account-pass=admin
    --db-url=mysql://drupal:1234@localhost/drupal
    --root=/var/www/drupal-8.6.5-dev
    creates=/var/www/drupal-8.6.5-dev/sites/default/settings.php
  notify: restart apache

- name: Set Settings.php permission 
  file:
    path: "/var/www/drupal-8.6.5-dev/sites/default/settings.php"
    mode: 0744

- name: Set Core files permission
  file:
    path: "/var/www/drupal-8.6.5-dev/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes


