---
- name: 1. Adding Ondrej Repo
  apt_repository: repo="ppa:ondrej/php" update_cache=yes

- name: 2. Installing PHP with other dependencies
  apt:
    state: present
    name:
      - git 
      - curl
      - unzip
      - apache2
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-json
      - php-mysql
      - php-mbstring

- name: 3. Installing MySQL server
  shell: apt-get remove mysql-server* mariadb-*

- name: 3. Start Apache, MySQL and PHP
  service: 
    name: {{ item }} 
    state: started 
    enabled: yes
  with_items:
    - apache2
    - mysql