--- 
- hosts: webservers
  gather_facts: false

  vars_files:
    - vars/vars.yml
  roles:
    - misc
    - php
    - mysql
    - nginx
    - bootstrap
    - code-deploy
  handlers:
    - include: handlers/main.yml