---
  - name: 1. Install MariaDB server
    apt: name=mariadb-server state=present

  - name: 2. Start MySQL service
    service: name=mysql state=started enabled=yes
  - name: 3. Install python MySQL packages
    apt: name=python-mysqldb state=present

  - name: 4. Create a new database
    mysql_db: name=demo state=present collation=utf8_general_ci

  - name: 5. Create a new database user
    mysql_user:
      name: demo
      password: demo
      priv: '*.*:ALL,GRANT'
      state: present

  - name: 6. Copy data dumb 
    copy: src=dump.sql dest=/tmp/dump.sql
  
  - name: 7. Insert the data to MySQL
    shell: cat /tmp/dump.sql | mysql -u demo -p demo demo
  
  - name: 8. Install MySQL PHP Ext 
    apt: name=php5-mysql state=present
  
  - name: 9. Restart Apache
    service: name=apache2 state=restarted
  
  - name: 10. Install Hello Wordl DB script
    copy: "src=db.php dest=/var/www/html/db.php mode=0664"