---
# tasks file for php
- name: Install https transport
  apt: name=apt-transport-https 
- name: Add gpg key
  shell: wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -

- name: Update source.list 
  shell: echo "deb https://packages.sury.org/php/ jessie main" | tee /etc/apt/sources.list.d/php.list

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install PHP {{php_version}}
  apt: name=php state=latest

- name: Install PHP packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-curl
    - php-fpm
    - php-intl
    - php-mysql
    - php-xml
    - php-mbstring
  notify: Restart PHP-FPM
  tags:
    - php